services:
  whisper-asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper-asr
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=whisper
      - ASR_COMPUTE_TYPE=float32
    volumes:
      - ./asr-models:/root/.cache
